name: Check Artifact

on:
  pull_request:
    branches:
      - main

jobs:
  check-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        uses: actions/checkout@v3
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Check if artifact exists
        run: |
          VERSION="data.table_1.16.4"
          if gh release list --repo "${{ github.repository }}" | grep -q "${VERSION}"; then
            echo "Artifact found!"
          else
            echo "Artifact not found!"
