name: Data Table PR Workflow

on:
  pull_request:
    branches: [ '**' ]  # Work with PRs from any fork
    types: [opened, synchronize, reopened]

env:
  R_VERSION: '4.2.2'
  ARTIFACT_PREFIX: 'data-table-pkg-'
  
jobs:
  check-and-install-data-table:
    runs-on: ubuntu-latest
    outputs:
      dt_version: ${{ steps.get-version.outputs.DT_VERSION }}
      installation_time: ${{ steps.timing.outputs.installation_time }}
      installation_method: ${{ steps.install-dt.outputs.installation_method }}
      artifact_size: ${{ steps.artifact-size.outputs.size }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
      
      - name: Get data.table version
        id: get-version
        run: |
          # Extract data.table version from DESCRIPTION or other config file
          # For this example, we'll set a specific version
          DT_VERSION="1.14.8"
          echo "DT_VERSION=$DT_VERSION" >> $GITHUB_ENV
          echo "DT_VERSION=$DT_VERSION" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=${{ env.ARTIFACT_PREFIX }}$DT_VERSION" >> $GITHUB_ENV
      
      - name: Check for cached data.table artifact
        id: check-cache
        uses: actions/cache@v3
        with:
          path: ~/r-packages/data.table
          key: ${{ env.ARTIFACT_NAME }}-${{ runner.os }}
      
      - name: Start timing
        id: timing-start
        run: |
          echo "start_time=$(date +%s)" >> $GITHUB_ENV
      
      - name: Install data.table from artifact
        id: install-dt
        run: |
          if [ "${{ steps.check-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Found cached version of data.table ${{ env.DT_VERSION }}"
            mkdir -p ~/R/library
            cp -r ~/r-packages/data.table ~/R/library/
            echo "installation_method=cache" >> $GITHUB_OUTPUT
          else
            echo "No cached version found, building from source..."
            # Install dependencies first
            Rscript -e 'install.packages(c("remotes"), repos = "https://cloud.r-project.org")'
            
            # Start measuring install time
            start_build=$(date +%s)
            
            # Install specific version of data.table
            Rscript -e 'remotes::install_version("data.table", version = "${{ env.DT_VERSION }}", force = TRUE, repos = "https://cloud.r-project.org")'
            
            # End measurement and calculate
            end_build=$(date +%s)
            build_time=$((end_build - start_build))
            echo "Build from source took $build_time seconds"
            
            # Create directory for caching
            mkdir -p ~/r-packages
            
            # Copy installed package to our cache directory
            pkg_path=$(Rscript -e 'cat(find.package("data.table"))')
            echo "Package installed at: $pkg_path"
            
            # Minify the package by removing unneeded files
            echo "Minifying package..."
            rm -rf $pkg_path/doc $pkg_path/demo $pkg_path/help $pkg_path/html
            find $pkg_path -name "*.Rd" -delete
            
            # Copy to cache location
            cp -r $pkg_path ~/r-packages/
            
            echo "installation_method=source" >> $GITHUB_OUTPUT
          fi
      
      - name: Calculate artifact size
        id: artifact-size
        run: |
          SIZE=$(du -sh ~/r-packages/data.table | cut -f1)
          echo "Artifact size: $SIZE"
          echo "size=$SIZE" >> $GITHUB_OUTPUT
      
      - name: Cache data.table for future runs
        if: steps.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/r-packages/data.table
          key: ${{ env.ARTIFACT_NAME }}-${{ runner.os }}
      
      - name: End timing and calculate
        id: timing
        run: |
          end_time=$(date +%s)
          installation_time=$((end_time - ${{ env.start_time }}))
          echo "Total installation time: $installation_time seconds"
          echo "installation_time=$installation_time" >> $GITHUB_OUTPUT
      
      - name: Verify installation
        run: |
          Rscript -e 'library(data.table); cat("data.table version:", packageVersion("data.table"), "\n")'
      
      - name: Log metrics as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const method = process.env.INSTALLATION_METHOD;
            const time = process.env.INSTALLATION_TIME;
            const size = process.env.ARTIFACT_SIZE;
            const methodText = method === 'cache' ? 'from cached artifact' : 'built from source';
            
            const body = `## data.table installation metrics
            - Version: ${process.env.DT_VERSION}
            - Installation method: ${methodText}
            - Installation time: ${time} seconds
            - Artifact size: ${size}
            
            ${method === 'cache' ? '✅ Using cached artifact saved build time!' : '⚠️ First run with this version - artifact cached for future runs'}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
        env:
          INSTALLATION_METHOD: ${{ steps.install-dt.outputs.installation_method }}
          INSTALLATION_TIME: ${{ steps.timing.outputs.installation_time }}
          ARTIFACT_SIZE: ${{ steps.artifact-size.outputs.size }}
          DT_VERSION: ${{ steps.get-version.outputs.DT_VERSION }}
  
  run-tests:
    needs: check-and-install-data-table
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
      
      - name: Restore cached data.table
        uses: actions/cache@v3
        with:
          path: ~/r-packages/data.table
          key: ${{ env.ARTIFACT_PREFIX }}${{ needs.check-and-install-data-table.outputs.dt_version }}-${{ runner.os }}
      
      - name: Install data.table from cache
        run: |
          mkdir -p ~/R/library
          cp -r ~/r-packages/data.table ~/R/library/
      
      - name: Run PR tests
        run: |
          echo "Running tests with data.table ${{ needs.check-and-install-data-table.outputs.dt_version }}"
          # Add your actual tests here
          Rscript -e 'library(data.table); print("Tests running successfully with data.table library")'

  fallback-build:
    needs: check-and-install-data-table
    runs-on: ubuntu-latest
    if: failure() && needs.check-and-install-data-table.result == 'failure'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
      
      - name: Fallback - Build data.table from source
        run: |
          # Extract version from job output or use default
          DT_VERSION="${{ needs.check-and-install-data-table.outputs.dt_version || '1.14.8' }}"
          
          echo "FALLBACK: Installing data.table v$DT_VERSION from source"
          
          # Install required packages
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          
          # Install specific version
          Rscript -e 'remotes::install_version("data.table", version = "'$DT_VERSION'", force = TRUE, repos = "https://cloud.r-project.org")'
      
      - name: Verify fallback installation
        run: |
          Rscript -e 'library(data.table); cat("Fallback data.table version:", packageVersion("data.table"), "\n")'
      
      - name: Run fallback tests
        run: |
          # Add your tests here
          Rscript -e 'library(data.table); print("Tests running with fallback data.table installation")'
